### ISSUE TITLE
Avalonia 11 预览版 11.1.0.beta-1 失效

### ISSUE THREAD

**Issue by emako** [Antelcat/I18N#10]
目前Avalonia 11最新版是：11.0.10，预览版是11.1.0.beta-1。

预览版失效了，似乎是因为这个方法：public static void Register(ExpandoObject target)的Assembly.GetAssembly(typeof(IPropertyAccessorPlugin)).GetType("Avalonia.Data.Core.ExpressionObserver")返回了null，好像预览版开始删除了ExpressionObserver这个类？

**Comment by feast107** [comment]
进行了一个很快的修。
`ExpressionObserver` 并没有消失，他被移动到了 ` Avalonia.Data.Core.Plugins.BindingPlugins` 并作为数个公开集合存在。
``` cs
BindingPlugins.PropertyAccessors.Add(yourPlugin);
```
比之前便捷了一些

**Comment by feast107** [comment]
[Nuget Antelcat.18N.Avalonia v1.0.2](https://www.nuget.org/packages/Antelcat.I18N.Avalonia/1.0.2)

**Comment by emako** [comment]
现在是11.0.10用Antelcat.18N.Avalonia v1.0.1，11.1.0.beta-1用Antelcat.18N.Avalonia v1.0.2这样子吗？

**Comment by feast107** [comment]
是的，原本的包一经提交就不可修改。而且Avalonia框架是通过nuget引用的，而不是MSbuild，没法通过宏来控制编译或者区别处理。只能通过这种依赖版本匹配的方式解决。
