### ISSUE TITLE
Avalonia 无法在新窗口下显示翻译

### ISSUE THREAD

**Issue by emako** [Antelcat/I18N#11]
![image](https://github.com/Antelcat/I18N/assets/24737061/8c48f77c-83b5-4b28-a092-8f56477162d6)

avalonia的默认模板下，就仅加了个Button，点击再new一个窗口
```c#
    private void Button_Tapped(object? sender, Avalonia.Input.TappedEventArgs e)
    {
        new MainWindow().Show();
    }
```

**Comment by emako** [comment]
示例工程：
[AvaloniaApplication1.zip](https://github.com/Antelcat/I18N/files/15139920/AvaloniaApplication1.zip)

**Comment by feast107** [comment]
在修了在修了，但这个问题似乎非常复杂，涉及到Avalonia的渲染生命周期，还在抢救中 
... To be continued

**Comment by emako** [comment]
NavigationView的Frame控件也会有同样的问题，似乎跟是否是新窗口没关系，似乎异步new的控件都会有问题

**Comment by feast107** [comment]
这事Avalonia的问题，我用他的Sample，对已经创建过的窗口再new一个就会这样失去绑定，基本的绑定也会丢失
![image](https://github.com/Antelcat/I18N/assets/82046714/7a069ac9-978b-4082-bb03-65d3e5041e8a)

**Comment by DearVa** [comment]
> 这事Avalonia的问题，我用他的Sample，对已经创建过的窗口再new一个就会这样失去绑定，基本的绑定也会丢失 ![image](https://private-user-images.githubusercontent.com/82046714/326729173-7a069ac9-978b-4082-bb03-65d3e5041e8a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0NzMxNDIsIm5iZiI6MTcxNDQ3Mjg0MiwicGF0aCI6Ii84MjA0NjcxNC8zMjY3MjkxNzMtN2EwNjlhYzktOTc4Yi00MDgyLWJiMDMtNjVkM2U1MDQxZThhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDMwVDEwMjcyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxYzBiNDJmMjVjYjkxMjBhOTVlNTZhNmQ2ZmM4YWY5MzY4ZWFkN2VjY2ZlODUzN2RhMTcxM2FhMmE0Njg2ZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3xTkC4HVV2O772sLQMImuleeg9ohxLdUrWHSlO1iKdU)

![image](https://github.com/Antelcat/I18N/assets/55902546/2beedeb8-1f16-44d2-a885-c3a8c21cf63c)
![image](https://github.com/Antelcat/I18N/assets/55902546/6901f8d0-b6ab-4e59-98a4-77b92c1a7d10)
创建新窗口时没有指定DataContext……Avalonia没有bug，自己的Binding不会失效，但是I18N会失效

**Comment by AuroraZiling** [comment]
改下Culture就好使了，奇怪（
![weird](https://github.com/Antelcat/I18N/assets/69903523/a1b4ed5c-ed07-4966-ad67-f63cc8de331d)

**Comment by feast107** [comment]
> 改下Culture就好使了，奇怪（
> ![weird](https://github.com/Antelcat/I18N/assets/69903523/a1b4ed5c-ed07-4966-ad67-f63cc8de331d)
> 

我目前发现的情况是当 `InitializeComponent` 的时候他会触发组件的ProvideValue，但这个时候BindingSource是空的，我还得重新跟踪一下他的生命周期

**Comment by feast107** [comment]
Latest update on Nuget [Antelcat.I18N.Avalonia/1.0.3](https://www.nuget.org/packages/Antelcat.I18N.Avalonia/1.0.3)

**Comment by feast107** [comment]
顺带一提，现在的修复方式还不是很完美，只是缓解了这个问题（暂时的）。不过目前已经移除了很大一部分的反射，Avalonia的CompileBinding有望（。
我们现在弄了个q群529877643可以交流

**Comment by emako** [comment]
（申请了

缓解是指随着Avalonia版本升级还有可能变化？，还是指有些场景下依然有问题？

**Comment by feast107** [comment]
Avalonia版本升级应该还会有变化，我看到他那个IBinding2的时候就已经难蚌了，原有的某些方法已经开始注释前情提要。
