### ISSUE TITLE
对现有软件添加多语言

### ISSUE THREAD

**Issue by shuairobin** [Antelcat/I18N#12]
对现有软件添加多语言，每个翻译的字符都要进行键来绑定语言源。有很多工作量很大，有没有简便的方法减少工作量。

**Comment by feast107** [comment]
如果是.xaml更改绑定可以用正则表达式批量替换，这样不容易遗漏

**Comment by shuairobin** [comment]
可否举个例子，谢谢！

**Comment by feast107** [comment]
我不了解你们原本使用的翻译方式，如果是绑定，且Key值一样，可以用正则表达式来批量替换

`{Binding ...} => {I18N {Binding ...}}`

![image](https://github.com/Antelcat/I18N/assets/82046714/146fe31b-4eb6-4534-80ec-b5bcdff244d7)
