### ISSUE TITLE
Header="{I18N {x:Static yP:LangKeys.File}}"

### ISSUE THREAD

**Issue by masonwu21** [Antelcat/I18N#13]
写在xaml中绑定时 显示Object of type 'System.String' cannot beconverted to type
System.Windows.Data.BindingBase'

编译可以通过使用，但这个警告如何消除
![image](https://github.com/Antelcat/I18N/assets/830761/be202b8d-58fa-4eb9-98f1-e49bbc09d8b0)

**Comment by feast107** [comment]
这个问题源自于 `I18NExtension` 的 `[MarkupExtensionReturnType(Type)]` 我之前的设置是 `typeof(string)` 如果改成 `typeof(BindingBase)` 
![image](https://github.com/Antelcat/I18N/assets/82046714/3123a4b8-a90f-4390-83aa-9bc88236a445)
