### ISSUE TITLE
Antelcat.Wpf.I18N提示弃用，但是Antelcat.I18N.WPF运行失败

### ISSUE THREAD

**Issue by breadgrocery** [Antelcat/I18N#15]
`Antelcat.Wpf.I18N`提示弃用了，使用`Antelcat.I18N.WPF`代替。
然而，`Antelcat.I18N.WPF`运行报错:（这个I.0是什么东西，是1.0写错了吗？）
```
未经处理的异常:  System.TypeInitializationException: “<Module>”的类型初始值设定项引发异常。 ---> System.IO.FileNotFoundException: 未能加载文件或程序集“Antelcat.I.0, Culture=neutral, PublicKeyToken=null”或它的某一个依赖项。系统找不到指定的文件。
   在 .cctor()
   --- 内部异常堆栈跟踪的结尾 ---
```
错误细节：
- Langkeys源代码正常生成，无报错
- xaml中正确引用访问，无警告无报错，可跳转
- xaml编辑器build后无法预览文字
- 启动程序直接异常退出

环境：
.Net development runtime: .Net 8.0
Target frameowrk: .net framework 4.6.2
IDE: Rider 2024.3.2

换回旧的`Antelcat.Wpf.I18N`正常工作.
无法预览貌似是Rider的问题，vs2022可以正常预览

**Comment by feast107** [comment]
能展示一下你的 .csproj 文件吗，更换为 `Antelcat.I18N.WPF` 之后的

**Comment by breadgrocery** [comment]
```
<Project Sdk="Microsoft.NET.Sdk">
    <!-- Project Configuration -->
    <PropertyGroup>
        <!-- Build Configuration -->
        <!-- Built-in Since Windows 10 Version 1607 (August 2, 2016) -->
        <TargetFramework>net462-windows</TargetFramework>
        <OutputType>WinExe</OutputType>
        <UseWPF>true</UseWPF>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <AppendRuntimeIdentifierToOutputPath>true</AppendRuntimeIdentifierToOutputPath>
        <!-- C# Language Features -->
        <LangVersion>12</LangVersion>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <!-- Project Dependencies -->
    <ItemGroup>
        <!-- MVVM support -->
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.3.2"/>
        <!-- Material Design UI -->
        <PackageReference Include="MaterialDesignThemes" Version="5.1.0"/>
        <!-- Assembly Merging -->
        <PackageReference Include="Costura.Fody" Version="6.0.0" PrivateAssets="all"/>
    </ItemGroup>

    <!-- Git Hooks Integration -->
    <Target Name="husky" BeforeTargets="Restore;CollectPackageReferences" Condition="'$(HUSKY)' != 0">
        <Exec Command="dotnet tool restore" WorkingDirectory="../"
              StandardOutputImportance="Low" StandardErrorImportance="High"/>
        <Exec Command="dotnet husky install" WorkingDirectory="../"
              StandardOutputImportance="Low" StandardErrorImportance="High"/>
    </Target>
</Project>

```

**Comment by breadgrocery** [comment]
这是demo，内容是旧版的，关注增加按钮的I18N，这版可以正常运行。
新版的我也写了（注释掉了），运行就报错。

[demo.zip](https://github.com/user-attachments/files/18144857/demo.zip)

~~另外，README中的TextBlock写错了，写成了TextBolck~~

**Comment by breadgrocery** [comment]
另外预览也还是有些问题。
- MainWindow.xaml中可以预览，但是得运行一次后才行，光build是不行的。
- 子Control的xaml就没法预览了，设计的时候看不到文字就很难受。

<img width="885" alt="1" src="https://github.com/user-attachments/assets/6ef58548-aacf-457e-8735-f46153ac17e1" />


<img width="977" alt="2" src="https://github.com/user-attachments/assets/ee650d65-9ae4-40a1-af59-a6e08c8e47ff" />

**Comment by feast107** [comment]
我用你的代码更换为`Antelcat.I18N.WPF`之后能够正常运行，可能是因为编译缓存的问题，更换包之后需要重新构建一下。
然后无法预览是因为I18N属于动态更换语言，运行时本身就会展示不同的内容，不可能是静态的，编译期也就无法得知需要展示什么内容。

**Comment by breadgrocery** [comment]
附上构建产物和pdb。
- old可以运行，删掉zh也能运行，只是不再翻译
[old.zip](https://github.com/user-attachments/files/18157438/old.zip)
- new则是完全不运行
[new.zip](https://github.com/user-attachments/files/18157436/new.zip)

**Comment by feast107** [comment]
你可以看下.NET本地化资源的加载方式。其他的程序集都在应用目录下，为什么这个程序集会嵌套一个目录。其他程序集缺失会无法启动，为什么本地化资源的程序集不加载也可以运行。届时你就知道为什么`Costura`没有打包这些程序集了

**Comment by breadgrocery** [comment]
这个貌似是Costura的一个[known issue](https://github.com/GuOrg/Gu.Localization/issues/40)，但是按照说的使用`Resource.Embedder`也没解决。
我还是试试xaml+切换Source的方案吧。

**Comment by breadgrocery** [comment]
解决方案里提到的`Gu.Localization`也是一个本地化框架，也是markup扩展，但是可以在vs2022中(Rider不行)正常预览欸（只需要build就可以，设计的时候也能看到文字）。

**Comment by feast107** [comment]
I18N支持{I18N {Binding ...}}，绑定内存字符串进行翻译，编译期是提供不了字符串源的。
