### ISSUE TITLE
[Bug] WPF: 动态更改的格式化字符串不显示插值内容

### ISSUE THREAD

**Issue by AuroraZiling** [Antelcat/I18N#6]
XAML:
![image](https://github.com/Antelcat/Antelcat.I18N/assets/69903523/cb51ee02-1ab9-4555-b337-3763af311cac)

Language:
![image](https://github.com/Antelcat/Antelcat.I18N/assets/69903523/caec0ed1-26e6-4761-9538-f97b9c7b4b51)

Effect:
![image](https://github.com/Antelcat/Antelcat.I18N/assets/69903523/a3743035-9b9c-414e-8e83-6afea1da7c68)

在一两个月前是没有问题的，不知道和`.net 8`的升级有没有关系

Package: `Antelcat.I18N.WPF 1.0.0`

**Comment by feast107** [comment]
我已经将项目中的[Demo](https://github.com/Antelcat/Antelcat.I18N/tree/main/src/WPF/Demo)提升到了.NET8，但他依然能正常工作，应该是没有拿到正确的值的问题

**Comment by AuroraZiling** [comment]
我在旁边加了一个textblock，值应该是能正常取到的
![image](https://github.com/Antelcat/I18N/assets/69903523/5c78e1c9-13a1-424f-88d8-3baabbca4056)
![image](https://github.com/Antelcat/I18N/assets/69903523/19268059-4647-40ee-ae74-86e4e6de8da8)

**Comment by feast107** [comment]
非常奇怪，RelativeResource也是被binding托管的，按理来说行为应该是完全一致的

**Comment by AuroraZiling** [comment]
更怪的是，我找了两个历史版本（当时开发没有问题的），现在运行也成这样了

**Comment by AuroraZiling** [comment]
更怪的是，我找了两个历史版本（当时开发没有问题的），现在运行也成这样了

**Comment by AuroraZiling** [comment]
![image](https://github.com/Antelcat/I18N/assets/69903523/d93b928d-925c-4a2c-83e5-437b6eafdfa4)
找到问题了，如果binding value的数据类型是int，需要显式转换为string才可以被插值
![image](https://github.com/Antelcat/I18N/assets/69903523/2b166c30-27fd-4c23-97ea-d1823dcb7278)
![image](https://github.com/Antelcat/I18N/assets/69903523/63bd7394-2165-4e82-b60c-0a9a3287a9fd)

**Comment by feast107** [comment]
> ![image](https://private-user-images.githubusercontent.com/69903523/293507230-d93b928d-925c-4a2c-83e5-437b6eafdfa4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwMzU4NjksIm5iZiI6MTcwNDAzNTU2OSwicGF0aCI6Ii82OTkwMzUyMy8yOTM1MDcyMzAtZDkzYjkyOGQtOTI1Yy00YTJjLTgzZTUtNDM3YjZlYWZkZmE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMxVDE1MTI0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkMDdjMDViZWE4NDQ3MjMyMDg2YjBmOWIzODZkNjZmZDk5OTIzYmUyYzE2NTBjZmNkY2NiM2MyYzJiN2EwMzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OnCfhAk0B2otaLRkQ1qmTP81hEcpUC-4RGU_ik1rVMM) 找到问题了，如果binding value的数据类型是int，需要显式转换为string才可以被插值 ![image](https://private-user-images.githubusercontent.com/69903523/293507328-2b166c30-27fd-4c23-97ea-d1823dcb7278.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwMzU4NjksIm5iZiI6MTcwNDAzNTU2OSwicGF0aCI6Ii82OTkwMzUyMy8yOTM1MDczMjgtMmIxNjZjMzAtMjdmZC00YzIzLTk3ZWEtZDE4MjNkY2I3Mjc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMxVDE1MTI0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxMWUxODU2ODQ2NmZlMTFlYTJlZDFkMzM4NmE0ZjhlZjMzN2M3NmZhZTY5MzgxOGU2ZmMwYWMxYzU0MzQzN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.n5NxjhV0QupomQOwxwEyFDLIzOO1sB20ljx6KOwFQLY) ![image](https://private-user-images.githubusercontent.com/69903523/293507273-63bd7394-2165-4e82-b60c-0a9a3287a9fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwMzU4NjksIm5iZiI6MTcwNDAzNTU2OSwicGF0aCI6Ii82OTkwMzUyMy8yOTM1MDcyNzMtNjNiZDczOTQtMjE2NS00ZTgyLWI2MGMtMGE5YTMyODdhOWZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMxVDE1MTI0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyODE4YWIwNzkzMzE4YzE5NTkzMTcxNWI4N2ZmNmQzZTQwZjJkYjZjNmE4MTI4MDJmOGE2ODNkNmMxNTI1ZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6cN5-Jx3B36kgFGGbJErtyVDVYOv9idD2ryp3wZkziA)

你的测试提醒了我，我找到了问题所在，在生成string模板的时候我会默认他为 `string`，而实际上他可能是其他可以直接通过`ToString()`表达的类型。我会修改并发布一个修订版本。可以试试还原你的代码，然后使用修复版本。

**Comment by feast107** [comment]
以及，辛苦大家这个时候还在帮我修复bug，元旦快乐

**Comment by AuroraZiling** [comment]
元旦快乐

**Comment by AuroraZiling** [comment]
还原后，新版本可用
