### ISSUE TITLE
I18N for .net framework 4.8 WPF,生成的代码是C#8的，在C#7.3下不支持。

### ISSUE THREAD

**Issue by superbug8848** [Antelcat/I18N#7]
我有一个老项目需要修改为支持多语言，该项目是.net framework 4.8的WFP，当前用Antelcat.I18N.Wpf，
自动生成的代码，编译报错：

错误	CS8370	功能“可为 null 的引用类型”在 C# 7.3 中不可用。请使用 8.0 或更高的语言版本。	WpfBrowserFrameConfig	D:\wisentbase\WPFUIFrame\WpfBrowserFrameConfig\Antelcat.I18N.SourceGenerators\Antelcat.I18N.WPF.SourceGenerators.Generators.ResourceKeysGenerator\WISDRI.WISENTBASE.WpfBrowserFrameConfig.Properties.LangKeys.g.cs	10	活动	

错误	CS8370	功能“模块初始值设定项”在 C# 7.3 中不可用。请使用 9.0 或更高的语言版本。	WpfBrowserFrameConfig	D:\wisentbase\WPFUIFrame\WpfBrowserFrameConfig\Antelcat.I18N.SourceGenerators\Antelcat.I18N.WPF.SourceGenerators.Generators.ResourceKeysGenerator\WISDRI.WISENTBASE.WpfBrowserFrameConfig.Properties.LangKeys.g.cs	29	活动	

能不能兼容一下老平台，谢谢了。

**Comment by feast107** [comment]
应该是 `#nullable enable ` 和 `[ModuleInitializer]` 特性导致的
库 `Antelcat.I18N.WPF` 支持最低框架版本 .NET Framework 4.0 , 完全兼容您正在使用的4.8, 
但是C#语言版本需要 >=9.0, 配置语言版本可以在项目文件 `.csproj` 中添加 `<LangVersion>9</LangVersion>` 
语言版本的提升**不会对您的代码产生任何影响**，可以放心的提升语言版本
还是说如果有坚持要使用7.3语言版本原因，请告诉我，我再做一些尝试

**Comment by superbug8848** [comment]
已经好了，谢谢

**Comment by DearVa** [comment]
提升语言版本会受到SDK的影响，这确实是一个潜在的问题，例如在只支持dotnet6的平台上，使用高版本的C#会导致无法编译
