### ISSUE TITLE
项目使用AntelCat.I18N.WPF后，用costora打包成单个可执行文件时，程序启动，提示无法找到Antelcat.I18N.Abstractions.dll

### ISSUE THREAD

**Issue by superbug8848** [Antelcat/I18N#8]
Antelcat.I18N.Abstractions.dll文件已经打包到可执行文件中，但启动时就是提示找不到。其它引用的库文件没有这个问题，这个库文件的引用有什么特别的地方吗？

**Comment by feast107** [comment]
`Antelcat.I18N.Abstractions` 提供了 `ResourceProvier`用于绑定、`ResourceKeysOfAttribute`特性生成代码，目前`I18N`是基于反射工作的。不知你使用的costora在打包的时候会对程序集进行什么处理

**Comment by emako** [comment]
@superbug8848 需要把resx跟LangKeys放到独立DLL里调用就能解决

**Comment by emako** [comment]
可参考https://github.com/GenshinMatrix/Fischless/tree/main/src/Common/Fischless.Globalization
